per:
  remark: 它在yaml中
#测试bean中的各种类型注入
yml:
  str: ningbin
  boo: true
  date: 2020/12/11 11:12:13
  i: 18
  pet:
    name: lulu
    weight: 9
  array: [football,swing]
  list:
    - jack
    - lucy
  map1:
    k1: v1
    k2: v2
  map2: {k1: v1,k2: v2}
  map3:
    map:
      k1: v1
      k2: v2
    set: [1,2,3]
    array: [4,5,6]
    list:
      - 1
      - 10
      - 100
  set: [1.0,1.1]
  mapAndList:
    k1:
      - {name: n1,weight: 1}
      - {name: n2,weight: 2}
    k2: [{name: n3,weight: 3},{name: n4,weight: 4}]
