spring:
  datasource:
    url: jdbc:mysql://139.159.196.163:3306/sg_blog?characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: FXLNMrtc2952qblCN
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
  redis:
    database: 0
    port: 7847
    password: 17kdjnwh288#68lwYWU&NKO910Y5DBULLAlautyf#%vbxz035kj25sdfyugweewv
    host: 139.159.196.163
  elasticsearch:
    uris: 139.159.196.163:9200
    username:
    password:
  freemarker:
    suffix: .ftl
    settings:
      classic_compatible: true